### ISSUE TITLE
Accept millisecond values with any number of digits

### ISSUE THREAD

**Issue by cpeterso** [mrrrgn/proposal-date-time-string-format#10]
parser.peg and ECMA-262's [sec-date-time-string-format](http://www.ecma-international.org/ecma-262/6.0/#sec-date-time-string-format) only accept three-digit milliseconds, but browsers accept milliseconds with any number of digits:

* `2016-01-31T00:01:23.4` should be parsed as 400 milliseconds.
* `2016-01-31T00:01:23.45` should be parsed as 450 milliseconds.
* `2016-01-31T00:01:23.456789` is parsed as 456 milliseconds, though silently losing precision seems like a bad idea.
 * Firefox also has some rounding bugs (like [bug 746529](https://bugzilla.mozilla.org/show_bug.cgi?id=746529)) with really long millisecond values:
   * `1970-01-01T00:00:00.99999999999999995` returns 999 milliseconds.
    * `1970-01-01T00:00:00.99999999999999996` is rounded up to the next second 1970-01-01T00:00:01.

**Comment by mrrrgn** [comment]
Oy, this one is tricky. My inclination is to propose 1 to 3 digits so that we're a little more flexible but still don't resort to truncating.

**Comment by mrrrgn** [comment]
Fixed in 851f24bb609b02d5b4b530a857c0f146bd58dcec (though my commit message is wrong, doh!)

**Comment by cpeterso** [comment]
So you decided to allow truncation of millisecond values > 999? I guess this makes because that's what browsers do.
