### ISSUE TITLE
MonthName and MonthNameEnd issues

### ISSUE THREAD

**Issue by cpeterso** [mrrrgn/proposal-date-time-string-format#13]
parser.peg accepts the following strings that are rejected by Firefox and Edge. These strings are accepted by Chrome.

```
jan . 1, 2016
jan ... 1 2016
jan zzz 1, 2016
```

parser.peg rejects the following strings that are accepted by Firefox, Edge, and Chrome:

```
janu 1, 2016
janua 1, 2016
januar 1, 2016
january 1, 2016
```

parser.peg rejects the following string that is accepted by Edge and Chrome. Firefox currently rejects this string; see [Firefox bug 1175778](https://bugzilla.mozilla.org/show_bug.cgi?id=1175778).

```
jan. 1, 2016
```

**Comment by mrrrgn** [comment]
Oy, good catch

**Comment by mrrrgn** [comment]
@cpeterso I'm going to get us a test sweet going tonight so that this stops happening. Plan is to generate some giant tables full of input/output pairs for SM and V8 (then Chakra).

**Comment by mrrrgn** [comment]
These strings are working now.
