### ISSUE TITLE
Does not support ISO 8601 with trailing "Z"

### ISSUE THREAD

**Issue by AVGP** [mrrrgn/proposal-date-time-string-format#2]
According to ISO 8601 the Zulu time (UTC) may be denoted with a trailing "Z" as the timezone offset like this:

```
2016-06-08T21:00:33Z
```

However, the parser does not like this yet and produces `SyntaxError: Expected "." or end of input but "Z" found.` instead of the time representation.

The existing parser from Chrome gives the correct date.

**Comment by mrrrgn** [comment]
Nice, thank you!
