### ISSUE TITLE
Day '30' produces SyntaxError: Expected " ", "T", [1] or end of input but "0" found.

### ISSUE THREAD

**Issue by cpeterso** [mrrrgn/proposal-date-time-string-format#5]
The parser doesn't handle day '30':
https://github.com/mrrrgn/proposal-date-time-string-format/blob/master/parser.peg#L98

`2001-01-30` and `2001-01-30T00:01:23.456` produce `SyntaxError: Expected " ", "T", [1] or end of input but "0" found.`

**Comment by mrrrgn** [comment]
Oy, that's embarrassing. thank you for reporting that! ^.^ Fixed in 2f520aa645c8cbede243733a070560b037d34e06
