### ISSUE TITLE
Make demo page slightly more robust

### ISSUE THREAD

**Issue by cvrebert** [mrrrgn/proposal-date-time-string-format#7]
Currently, if I enter a value which the PEG can't parse but my browser's `new Date()` can parse, I'm only shown the PEG's SyntaxError. For convenience of testing & comparison, the result of the browser's parser should always also be shown, IMHO.

**Comment by mrrrgn** [comment]
Good point!

**Comment by mrrrgn** [comment]
Fixed in 79fb63d2935a18e52d6bd7f6c76150da54749259
