### ISSUE TITLE
Month name quirks

### ISSUE THREAD

**Issue by cpeterso** [mrrrgn/proposal-date-time-string-format#9]
parser.peg does not accept `JaNu 31, 2016` but browsers do:

`SyntaxError: Expected "apr", "aug", "dec", "feb", "jan", "jul", "jun", "mar", "may", "nov", "oct", "sep", [+-], [0-9], [0], [1-9], [1], [2] or [3] but "J" found.`

Here are some browser quirks I've found when parsing month names:

* Firefox, Chrome, Safari, IE11, and Edge **accept case-insensitive month names** like `JaN`.
* Firefox, Chrome, Safari, IE11, and Edge **accept prefixes of month names**, e.g. `Jan`, `Janu`, `Janua`, `Januar`, and `January` are all parsed as January.
* Periods following month names:
 * Firefox does not accept a period after month names like `Jan.`. This is [Firefox bug 1175778](https://bugzilla.mozilla.org/show_bug.cgi?id=1175778).
 * IE11 and Edge **accept a period immediately following a month name** (no spaces) like `Jan.` and `January.` but not `Jan .` or `January .`.
 * Chrome and Safari will accept periods and random crap pretty much anywhere in month name, e.g. `JanZ ..Zu.aZ.r.Zzy.Z. 1 .... 2016` is parsed as 2016-01-01.

**Comment by mrrrgn** [comment]
Sweet baby goodness, this is awesome to know. /me thinks now [or tomorrow am] would be a good time to start compiling a corpus of test cases.

**Comment by mrrrgn** [comment]
Expanded further in commit: d4699f84d6800c7854bc772f550304e4016e5623
